language: python
dist: xenial

env:
  global:
    - PROJECT_DIR="$HOME/project"

python:
  - "3.7"

install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
  - bash /tmp/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda config --add channels bioconda
  - conda config --add channels conda-forge

  # build package with cond
  - conda install conda-build
  - conda build conda.recipe --output-folder=$HOME/build
  - conda config --add channels "file://${HOME}/build"

  # test package
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda create -q -n drop drop
  - conda activate drop

before_script:
  - mkdir -p $PROJECT_DIR
  - cd $PROJECT_DIR
  - drop demo

script: 
  - conda list 
  - java -version
  - gatk --help
  - samtools --version
  - bcftools --version
  - drop --version
  - python --version

  # run pipeline
  - snakemake -n
  - snakemake aberrantExpression --cores 2
  - snakemake aberrantSplicing --cores 2
  - snakemake mae --cores 2
  - snakemake --cores 2
  - snakemake exportCounts --cores 2
