language: python
dist: xenial

cache:
  - directories:
    - $HOME/miniconda

python:
  - "3.6.7"

install:
  - bash travis/install_conda.sh
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda update conda

  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda config --add channels anaconda

  - conda install conda-build
  - conda build conda.recipe --python=$TRAVIS_PYTHON_VERSION --output-folder=$HOME/build
  - conda config --add channels "file://${HOME}/build"

  - conda config --get channels
  - conda create -q -n drop python=$TRAVIS_PYTHON_VERSION drop
  - conda activate drop

  - java -version
  - gatk --help
  - samtools --version
  - bcftools --version
  - drop --version


script: true
