language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library

python:
  - "3.6.7"

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n drop_env python=$TRAVIS_PYTHON_VERSION
  - conda activate drop_env
  - python --version
  - conda install -c bioconda gatk4 samtools=1.7.0 bcftools=1.7.0
  - java -version
  - alias gatk='gatk-launch'
  - gatk --help
  - samtools --version
  - bcftools --version

addons:
  apt:
    packages:
      - r-base
#      - libxml2-dev
#      - tk-dev
#      - libgit2-dev

install:
  - pip install -e .
  - R -e "message(.libPaths())"
  - mkdir ~/project
  - cd ~/project
  - drop init

script:
  - snakemake -n
