language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library
    - /usr/bin/R
    - $HOME/miniconda

env:
  global:
    - DROP_DIR=$(pwd)
    - PROJECT_DIR="$HOME/project"
    - MINICONDA_DIR="$HOME/miniconda"
    - CONDA_SCRIPT="$MINICONDA_DIR/etc/profile.d/conda.sh"
    - R_LIBS_USER="$HOME/R/Library"
    - TAR="/bin/tar"

python:
  - "3.6.7"

addons:
  apt:
    packages:
      - r-base
      - libxml2-dev
#      - tk-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
    sources:
      - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xe298a3a825c0d65dfd57cbb651716619e084dab9'

#before_cache:
#  - mkdir -p $R_LIBS_USER
#  - chmod -R 777 $R_LIBS_USER
#  - mkdir -p $MINICONDA_DIR
  
install:
  - cd $DROP_DIR
  - Rscript travis/installRPackages.R OUTRIDER
  - Rscript travis/installRPackages.R c-mertes/FraseR
  - Rscript travis/installRPackages.R mumichae/tMAE
  - echo $CONDA_SCRIPT
  - bash travis/activate_conda.sh
  - source $CONDA_SCRIPT
  - conda activate drop_env
  - pip install .

#before_script:
#  - cd $DROP_DIR
#  - mkdir -p $PROJECT_DIR
#  - bash travis/download_data.sh
#  - cd $PROJECT_DIR
#  - drop init
#  - travis_wait 30 snakemake -n

#script:
#  - snakemake

script: true

