language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library

python:
  - "3.6.7"

addons:
  apt:
    packages:
      - r-base
#      - libxml2-dev
#      - tk-dev
#      - libgit2-dev

before_install:
  - DROP_DIR=$(pwd)
  - cd $HOME
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n drop_env python=$TRAVIS_PYTHON_VERSION
  - conda activate drop_env
  - python --version
  - conda install -c bioconda gatk4=4.0.4.0 samtools=1.7.0 bcftools=1.7.0
  - java -version
  #- alias gatk='gatk-launch'
  - gatk --help
  - samtools --version
  - bcftools --version
  - cd ${DROP_DIR}

install:
  - pip install .
  - R -e "message(.libPaths())"
  - cd $HOME
  - mkdir project
  - cd project
  - wget -nc "https://i12g-gagneurweb.informatik.tu-muenchen.de/public/paper/drop_analysis/resource.tar.gz"
  - tar -zxvf resource.tar.gz
  - mv resource Data
  - cd Data
  - python fix_sample_anno.py
  - cd ..
  - drop init

script:
  - snakemake

