language: python
sudo: required
dist: xenial
#cache:
#  - directories:
#    - $HOME/R/Library

addons:
  apt:
    packages:
      - r-base
#      - libxml2-dev
#      - tk-dev
#      - libgit2-dev

python:
  - "3.7"

install:
  - pip install -e .

script:
  - pytest
