language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library
    - /usr/bin/R
    - $HOME/miniconda
    - $HOME/project/Data

env:
  global:
    - DROP_DIR=$(pwd)
    - PROJECT_DIR="$HOME/project"
    - MINICONDA_DIR="$HOME/miniconda"
    - R_LIBS_USER="$HOME/R/Library"
    - export TAR="/bin/tar"

python:
  - "3.6.7"

addons:
  apt:
    packages:
      - r-base
      - libxml2-dev
      #- tk-dev
      - libcurl4-openssl-dev
      - libssl-dev
    sources:
      - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xe298a3a825c0d65dfd57cbb651716619e084dab9'

before_cache:
  - mkdir -p $R_LIBS_USER
  - mkdir -p $PROJECT_DIR
  
before_install:
  - echo $DROP_DIR
  - bash travis/download_data.sh
  - bash travis/activate_conda.sh

install:
  - conda activate drop_env
  - cd ${DROP_DIR}
  - pip install .
  - R -e "print(.libPaths())"
  - R -e "install.packages('data.table')"

before_script:
  - cd $HOME/project/Data
  - python fix_sample_anno.py
  - cd $HOME/project/
  - drop init
  - travis_wait 30 snakemake -n

script:
  - snakemake

