---
webDir: /s/public_webshare/public/genetic_diagnosis_demo/webDir
projectTitle: Demo Project
htmlOutputPath: Output/html
fileRegex: .*\.R

DATASET_NAME: genetic_diagnosis_demo

# OUTPUT Directory
ROOT: /s/public_webshare/public

# INPUT: Sample annotation
SAMPLE_FILE_MAPPING: /s/public_webshare/public/genetic_diagnosis_demo/raw_data/filemapping.tsv
SAMPLE_ANNOTATION: /s/public_webshare/public/genetic_diagnosis_demo/raw_data/sample_annotation.tsv  
# For SAMPLE_FILE_MAPPING: assays
rna_assay: RNA_ID
dna_assay: DNA_ID

# INPUT: Gene Annotation
GENE_ANNOTATION: {"v29": "/s/public_webshare/public/genetic_diagnosis_demo/raw_data/annotation/gencode.v29lift37.annotation.gtf.gz"}
CHROMOSOME_FORMAT_rna: UCSC
CHROMOSOME_FORMAT_dna: NCBI



#### Aberrant Expression
## count settings
strand_column: COUNT_AS_STRANDED
paired_end_column: PAIRED_END
count_mode_column: COUNT_MODE
inter_feature_column: COUNT_OVERLAP
## outrider settings
outrider_group: OUTRIDER_GROUP ### also for splicing 
min_outrider_ids: 1
fpkmCutoff: 1


#### Monoallelic Expression
gene_assembly: "hg19"
VEP_VERSION: 94 


#### Aberrant Splicing
DATASETS: [
    "all",
    "small",
    ]

