name: drop_test
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - pip
  - drop
  - flake8
  - bioconductor-bsgenome.hsapiens.ucsc.hg19

  # required for downloading R packages through github
  - unzip
