projectTitle: Detection of RNA Outlier Pipeline
root:             # root directory of all intermediate output
htmlOutputPath:   # path for HTML rendered reports

# settings for wBuild - do not change
indexWithFolderName: true
fileRegex: .*\.R

sampleAnnotation: # path to sample annotation (see documenation on how to create it)

geneAnnotation:
    v29:          # path to gencode v29 annotation

aberrantExpression:
    groups: outrider
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zscoreCutoff: 0

aberrantSplicing:
    groups: fraser
    recount: true
    longRead: false
    minExpressionInOneSample: 20
    correction: PCA
    padjCutoff: 0.05
    zScoreCutoff: 0
    deltaPsiCutoff: 0.3

mae:
    groups:
        - group1
        - group2
    geneAssembly: hg19
    genome:       # path to genome sequence in fasta format
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    # VCF-BAM matching
    qcVcf:        # path to common variantqc_vcf_1000G.vcf.gz
    qcGroup: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

