projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: ~/project/Output/htmlOutput
indexWithFolderName: true
fileRegex: .*\.R

root: ~/project/Output
sampleAnnotation: ~/project/Data/sample_annotation.tsv
geneAnnotation: {
    v29: ~/project/Data/gencode.v29lift37.annotation.gtf.gz
}

aberrantExpression: {
    minIds: 1,
    fpkmCutoff: 1,
    groups: null,
    padjCutoff: .05,
    zscoreCutoff: 0,
    useGeneNames: true
}

aberrantSplicing: {
    groups: null,
    minIds: 10,
    deltaPsiCutoff : 0.05
}

mae: {
    geneAssembly: hg19,
    genome: ~/project/Data/hg19.fa,
    gatkIgnoreHeaderCheck: true,
    padjCutoff: .05,
    allelicRatioCutoff: 0.8,
    maxAF: .001,
    groups: null,
    # VCF-BAM matching
    qcVcf: {
        UCSC: ~/project/Data/qc_vcf_ucsc_1000G.vcf.gz,
        NCBI: ~/project/Data/qc_vcf_ncbi_1000G.vcf.gz
     },
    qcGroup: all
}

tools: {
    gatkCmd: gatk,
    bcftoolsCmd: bcftools,
    samtoolsCmd: samtools
}
