projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: /home/travis/project/Output/htmlOutput
indexWithFolderName: true
fileRegex: .*\.R

root: /home/travis/project/Output
sampleAnnotation: /home/travis/project/Data/sample_annotation.tsv
geneAnnotation: {
    v29: /home/travis/project/Data/gencode_annotation_trunc.gtf
}

aberrantExpression: {
    groups: outrider,
    fpkmCutoff: 1,
    padjCutoff: .05,
    zscoreCutoff: 0,
    useGeneNames: true
}

aberrantSplicing: {
    groups: fraser,
    deltaPsiCutoff : 0.05
}

mae: {
    geneAssembly: hg19,
    genome: /home/travis/project/Data/chr21.fa,
    gatkIgnoreHeaderCheck: true,
    padjCutoff: .05,
    allelicRatioCutoff: 0.8,
    maxAF: .001,
    gnomAD: false,
    groups: mae,
    # VCF-BAM matching
    qcVcf: {
        UCSC: /home/travis/project/Data/qc_vcf_ucsc_1000G.vcf.gz,
        NCBI: /home/travis/project/Data/qc_vcf_ncbi_1000G.vcf.gz
     },
    qcGroup: mae
}

tools: {
    gatkCmd: gatk,
    bcftoolsCmd: /home/travis/bcftools/bcftools,
    samtoolsCmd: samtools
}

