---
webDir: 
projectTitle: 
htmlOutputPath: 
indexWithFolderName: true ### if True then the index name will be the name of the parent of scripts dir: <dir>_index.html
fileRegex: .*\.R

# OUTPUT Directories for processed data & results:<ROOT>/<DATASET_NAME>/processed_data & <ROOT>/<DATASET_NAME>/processed_results
ROOT: 
DATASET_NAME: 

# INPUT: Sample annotation
SAMPLE_FILE_MAPPING: 
SAMPLE_ANNOTATION: 

# INPUT: Gene Annotation
GENE_ANNOTATION: {"v29": <path-to-gtf>}

#### Aberrant Expression
min_outrider_ids: 1
fpkmCutoff: 1
outrider_groups: null

#### Monoallelic Expression
gene_assembly: # "hg19"
genome: # fasta file
chr_names : ["chr1"] # list of chromosome names
gatk: gatk ## name of gatk command, assumed is version 4
gatk_sanity_check: true
qc_vcf: # vcf file (selected variants) for QC
qc_group: # name of group for QC

#### Aberrant Splicing
fraser_groups: null
min_fraser_ids: 10
