projectTitle: Detection of RNA Outlier Pipeline
root:             # root directory of all intermediate output
htmlOutputPath:   # path for HTML rendered reports

# settings for wBuild - do not change
indexWithFolderName: true
fileRegex: .*\.R

sampleAnnotation: # path to sample annotation (see documenation on how to create it)

geneAnnotation:
    # multiple annotations with custom names are possible
    # <annotation_name> : <path to gencode v29 annotation>
    v29:  /path/to/gencode29.gtf.gz # example

aberrantExpression:
    groups: 
        - group1
        - group2
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zscoreCutoff: 0

aberrantSplicing:
    groups:
        - group1
    recount: false
    longRead: false
    minExpressionInOneSample: 20
    correction: PCA
    padjCutoff: 0.05
    zScoreCutoff: 0
    deltaPsiCutoff: 0.3

mae:
    groups:
        - group1
        - group2
        - group3
    geneAssembly: hg19
    genome:       # path to genome sequence in fasta format
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    # VCF-BAM matching
    qcVcf:        # path to common variant file e.g. qc_vcf_1000G.vcf.gz
    qcGroup: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

