projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: /home/travis/project/Output/htmlOutput
indexWithFolderName: true
fileRegex: .*\.R

root: /home/travis/project/Output
sampleAnnotation: /home/travis/project/Data/sample_annotation.tsv
geneAnnotation:
    v29: /home/travis/project/Data/gencode_annotation_trunc.gtf

aberrantExpression:
    groups: outrider
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 1
    zscoreCutoff: 0

aberrantSplicing:
    groups: fraser
    recount: true
    longRead: false
    filter: false
    minExpressionInOneSample: 20
    correction: PCA
    padjCutoff: 1
    zScoreCutoff: 0
    deltaPsiCutoff : 0.05

mae:
    groups: mae
    geneAssembly: hg19
    genome: /home/travis/project/Data/chr21.fa
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    # VCF-BAM matching
    qcVcf: /home/travis/project/Data/qc_vcf_1000G.vcf.gz
    qcGroup: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: /home/travis/bcftools/bcftools
    samtoolsCmd: samtools

