name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda install -c conda-forge -c bioconda drop
        pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --builtins="snakemake" --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
      #run: |
        #conda install pytest
        #pip install -r tests/requirements.txt
        #pytest tests/pipeline/test_RVC.py
        ##pytest 
    - name: Test and Commit files # commit the output folder
      if: always()
      run: |
        conda install pytest
        pip install -r tests/requirements.txt
        #pytest 
        pytest tests/pipeline/test_RVC.py
        mkdir -p workflow_output
        git config --local user.email "test@github.com"
        git config --local user.name "GitHub Action test"
        echo "Hello World2" > workflow_output/test.txt
        yes| cp -rf '/tmp/pytest-of-runner/pytest-0/demo_dir0/Output/processed_data/rnaVariantCalling' ./workflow_output
        git add ./workflow_output
        git commit -m "Add changes"
        drop demo # should fail
    - name: Push changes # push the output folder to your repo
      if: always()
      uses: ad-m/github-push-action@master
      with:
        branch: RVC_dev #ignore if your branch is master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
